# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0003_auto_20151226_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='SapID',
            field=models.IntegerField(default=60000000000, unique=True),
        ),
    ]
